/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metadata */
        get: operations["get_metadata_api_v1_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Geojson */
        get: operations["get_geojson_api_v1_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trends */
        get: operations["get_trends_api_v1_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provinces */
        get: operations["get_provinces_api_v1_provinces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dimensions */
        get: operations["get_dimensions_api_v1_dimensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dynamics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dynamics */
        get: operations["get_dynamics_api_v1_dynamics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnualChangeArtifact */
        AnnualChangeArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["AnnualChangeRow"][];
            /** Largestincreaseyear */
            largestIncreaseYear: number | null;
            /** Largestincrease */
            largestIncrease: number | null;
            /** Largestdecreaseyear */
            largestDecreaseYear: number | null;
            /** Largestdecrease */
            largestDecrease: number | null;
        };
        /** AnnualChangeRow */
        AnnualChangeRow: {
            /** Year */
            year: number;
            /** Score */
            score: number | null;
            /** Previousscore */
            previousScore: number | null;
            /** Change */
            change: number | null;
            /** Contributorn */
            contributorN: number;
            /** Previouscontributorn */
            previousContributorN: number;
            /** Baseline */
            baseline: boolean;
        };
        /** Benchmark */
        Benchmark: {
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Provincescore */
            provinceScore: number | null;
            /** Regionmean */
            regionMean: number | null;
            /** Nationalmean */
            nationalMean: number | null;
            /** Nationalmin */
            nationalMin: number | null;
            /** Nationalmax */
            nationalMax: number | null;
            /** Nationalq1 */
            nationalQ1: number | null;
            /** Nationalq3 */
            nationalQ3: number | null;
            /** Vsregion */
            vsRegion: number | null;
            /** Vsnational */
            vsNational: number | null;
            /** Regionn */
            regionN: number;
            /** Nationaln */
            nationalN: number;
            /** Rankregion */
            rankRegion: number;
            /** Regiontotal */
            regionTotal: number;
        };
        /** CentroidRow */
        CentroidRow: {
            /** Cluster */
            cluster: string;
            /** N */
            n: number;
            /** D1 */
            D1?: number | null;
            /** D2 */
            D2?: number | null;
            /** D3 */
            D3?: number | null;
            /** D4 */
            D4?: number | null;
            /** D5 */
            D5?: number | null;
            /** D6 */
            D6?: number | null;
            /** D7 */
            D7?: number | null;
            /** D8 */
            D8?: number | null;
        };
        /** ChangeDistributionArtifact */
        ChangeDistributionArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** Fromyear */
            fromYear: number;
            /** Toyear */
            toYear: number;
            /** Median */
            median: number | null;
            /** Positiven */
            positiveN: number;
            /** Negativen */
            negativeN: number;
            /** Unchangedn */
            unchangedN: number;
            /** Positivepercentage */
            positivePercentage: number;
            /** Bins */
            bins: components["schemas"]["HistogramBin"][];
            /** Rows */
            rows: components["schemas"]["ChangeRow"][];
        };
        /** ChangeRow */
        ChangeRow: {
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Fromscore */
            fromScore: number | null;
            /** Toscore */
            toScore: number | null;
            /** Change */
            change: number | null;
        };
        /** ChangesArtifact */
        ChangesArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** Median */
            median: number | null;
            /** Rows */
            rows: components["schemas"]["ChangeRow"][];
            /** Top8 */
            top8: components["schemas"]["ChangeRow"][];
            /** Bottom8 */
            bottom8: components["schemas"]["ChangeRow"][];
        };
        /** ClusterArtifact */
        ClusterArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** Count */
            count: number;
            /**
             * Randomstate
             * @constant
             */
            randomState: 42;
            /** Rows */
            rows: components["schemas"]["ClusterRow"][];
            /** Centroids */
            centroids: components["schemas"]["CentroidRow"][];
            /** Profiles */
            profiles: components["schemas"]["ClusterProfile"][];
        };
        /** ClusterAssignment */
        ClusterAssignment: {
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Startcluster */
            startCluster: string;
            /** Endcluster */
            endCluster: string;
            /** Changed */
            changed: boolean;
            /** Startpc1 */
            startPc1: number | null;
            /** Startpc2 */
            startPc2: number | null;
            /** Endpc1 */
            endPc1: number | null;
            /** Endpc2 */
            endPc2: number | null;
        };
        /** ClusterCandidate */
        ClusterCandidate: {
            /** K */
            k: number;
            /** Silhouette */
            silhouette: number | null;
        };
        /** ClusterCentroidValue */
        ClusterCentroidValue: {
            /** Code */
            code: string;
            /** Zscore */
            zScore: number | null;
            /** Rawscore */
            rawScore: number | null;
        };
        /** ClusterProfile */
        ClusterProfile: {
            /** Cluster */
            cluster: string;
            /** N */
            n: number;
            /** Provinces */
            provinces: components["schemas"]["ClusterProvince"][];
        };
        /** ClusterProvince */
        ClusterProvince: {
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
        };
        /** ClusterRow */
        ClusterRow: {
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Cluster */
            cluster: string;
            /** D1 */
            D1?: number | null;
            /** D2 */
            D2?: number | null;
            /** D3 */
            D3?: number | null;
            /** D4 */
            D4?: number | null;
            /** D5 */
            D5?: number | null;
            /** D6 */
            D6?: number | null;
            /** D7 */
            D7?: number | null;
            /** D8 */
            D8?: number | null;
        };
        /** ClusterTransition */
        ClusterTransition: {
            /** Fromcluster */
            fromCluster: string;
            /** Tocluster */
            toCluster: string;
            /** N */
            n: number;
            /** Provinces */
            provinces: string[];
        };
        /** CorrelationArtifact */
        CorrelationArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** Codes */
            codes: string[];
            /** Matrix */
            matrix: (number | null)[][];
            /** Counts */
            counts: number[][];
            /** Strengths */
            strengths: string[][];
        };
        /** CovidArtifact */
        CovidArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Available */
            available: boolean;
            /** Rows */
            rows: components["schemas"]["CovidComparison"][];
        };
        /** CovidComparison */
        CovidComparison: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Beforescore */
            beforeScore: number | null;
            /** Afterscore */
            afterScore: number | null;
            /** Change */
            change: number | null;
            /** Contributornbefore */
            contributorNBefore: number;
            /** Contributornafter */
            contributorNAfter: number;
        };
        /** DeltaArtifact */
        DeltaArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["DeltaPoint"][];
        };
        /** DeltaPoint */
        DeltaPoint: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Delta */
            delta: number | null;
            /** Fromscore */
            fromScore: number | null;
            /** Toscore */
            toScore: number | null;
            /** Contributornfrom */
            contributorNFrom: number;
            /** Contributornto */
            contributorNTo: number;
        };
        /** DimensionAvailability */
        DimensionAvailability: {
            /** Dimensions */
            dimensions: string[];
        };
        /** DimensionFilters */
        DimensionFilters: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "six" | "eight";
            /** Year */
            year: number;
            /** X */
            x: string;
            /** Y */
            y: string;
        };
        /** DimensionInsights */
        DimensionInsights: {
            /** Correlation */
            correlation: string;
            /** Pair */
            pair: string;
            /** Residual */
            residual: string;
            /** Variation */
            variation: string;
        };
        /** DimensionPoint */
        DimensionPoint: {
            /** Year */
            year: number;
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Score */
            score: number | null;
            /** Contributorn */
            contributorN: number;
        };
        /** DimensionSeriesArtifact */
        DimensionSeriesArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["DimensionPoint"][];
        };
        /** DimensionsData */
        DimensionsData: {
            availability: components["schemas"]["DimensionAvailability"];
            correlation: components["schemas"]["CorrelationArtifact"];
            pair: components["schemas"]["PairArtifact"];
            standardDeviation: components["schemas"]["StdArtifact"];
            regression: components["schemas"]["RegressionArtifact"];
            /** Labels */
            labels: components["schemas"]["Indicator"][];
            insights: components["schemas"]["DimensionInsights"];
        };
        /** DimensionsMeta */
        DimensionsMeta: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "v1";
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /**
             * N
             * @description Số quan sát hợp lệ của input chính, không phải số hàng hiển thị
             */
            n: number;
            /** Caveats */
            caveats?: string[];
            filters: components["schemas"]["DimensionFilters"];
        };
        /** DimensionsResponse */
        DimensionsResponse: {
            meta: components["schemas"]["DimensionsMeta"];
            data: components["schemas"]["DimensionsData"];
        };
        /** DistributionArtifact */
        DistributionArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["DistributionRow"][];
        };
        /** DistributionRow */
        DistributionRow: {
            /** Provinceid */
            provinceId: number;
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Year */
            year: number;
            /** Rank */
            rank: number;
        };
        /** DynamicsData */
        DynamicsData: {
            measure: components["schemas"]["Measure"];
            changes: components["schemas"]["ChangesArtifact"];
            clusters: components["schemas"]["ClusterArtifact"];
            clusterModel: components["schemas"]["StableClusterArtifact"];
        };
        /** DynamicsFilters */
        DynamicsFilters: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "six" | "eight";
            /** From */
            from: number;
            /** To */
            to: number;
            /** K */
            k: number | "auto";
        };
        /** DynamicsMeta */
        DynamicsMeta: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "v1";
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /**
             * N
             * @description Số quan sát hợp lệ của input chính, không phải số hàng hiển thị
             */
            n: number;
            /** Caveats */
            caveats?: string[];
            filters: components["schemas"]["DynamicsFilters"];
        };
        /** DynamicsResponse */
        DynamicsResponse: {
            meta: components["schemas"]["DynamicsMeta"];
            data: components["schemas"]["DynamicsData"];
        };
        /** EmptyFilters */
        EmptyFilters: Record<string, never>;
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            } | null;
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["GeoFeature"][];
        };
        /** FocusPoint */
        FocusPoint: {
            /** Year */
            year: number;
            /**
             * Scope
             * @enum {string}
             */
            scope: "region" | "province";
            /** Label */
            label: string;
            /** Score */
            score: number | null;
            /** Contributorn */
            contributorN: number;
        };
        /** FocusSeriesArtifact */
        FocusSeriesArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["FocusPoint"][];
        };
        /** GeoFeature */
        GeoFeature: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            properties: components["schemas"]["GeoProperties"];
            geometry: components["schemas"]["GeoGeometry"];
        };
        /** GeoGeometry */
        GeoGeometry: {
            /**
             * Type
             * @enum {string}
             */
            type: "Polygon" | "MultiPolygon";
            /** Coordinates */
            coordinates: number[][][] | number[][][][];
        };
        /** GeoProperties */
        GeoProperties: {
            /** Province Id */
            province_id: number;
            /** Province Vi */
            province_vi: string;
            /** Shapename */
            shapeName: string;
        };
        /** GeojsonData */
        GeojsonData: {
            geojson: components["schemas"]["FeatureCollection"];
        };
        /** GeojsonResponse */
        GeojsonResponse: {
            meta: components["schemas"]["MetadataMeta"];
            data: components["schemas"]["GeojsonData"];
        };
        /** HistogramBin */
        HistogramBin: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** Center */
            center: number;
            /** Count */
            count: number;
            /** Percentage */
            percentage: number;
            /** Provinces */
            provinces: string[];
        };
        /** Indicator */
        Indicator: {
            /** Code */
            code: string;
            /** Namevi */
            nameVi: string;
            /** Nameen */
            nameEn: string;
            /** Short */
            short: string;
            /** Color */
            color: string;
            /** Sort */
            sort: number;
            /** Fromyear */
            fromYear: number;
        };
        /** Measure */
        Measure: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
        };
        /** MetadataData */
        MetadataData: {
            /** Scales */
            scales: components["schemas"]["ScaleAvailability"][];
            /** Dimensions */
            dimensions: components["schemas"]["Indicator"][];
            /** Regions */
            regions: string[];
            /** Provinces */
            provinces: components["schemas"]["Province"][];
        };
        /** MetadataMeta */
        MetadataMeta: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "v1";
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /**
             * N
             * @description Số quan sát hợp lệ của input chính, không phải số hàng hiển thị
             */
            n: number;
            /** Caveats */
            caveats?: string[];
            filters: components["schemas"]["EmptyFilters"];
        };
        /** MetadataResponse */
        MetadataResponse: {
            meta: components["schemas"]["MetadataMeta"];
            data: components["schemas"]["MetadataData"];
        };
        /** OverviewData */
        OverviewData: {
            measure: components["schemas"]["Measure"];
            metrics: components["schemas"]["OverviewMetrics"];
            map: components["schemas"]["OverviewMapArtifact"];
            ranking: components["schemas"]["RankingArtifact"];
            storyCards: components["schemas"]["OverviewStoryCards"];
            insights: components["schemas"]["OverviewInsights"];
        };
        /** OverviewInsights */
        OverviewInsights: {
            /** Map */
            map: string;
            /** Annualchange */
            annualChange: string;
            /** Quadrants */
            quadrants: string;
            /** Changedistribution */
            changeDistribution: string;
        };
        /** OverviewMapArtifact */
        OverviewMapArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["OverviewMapRow"][];
        };
        /** OverviewMapRow */
        OverviewMapRow: {
            /** Provinceid */
            provinceId: number;
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Rank */
            rank: number;
        };
        /** OverviewMeta */
        OverviewMeta: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "v1";
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /**
             * N
             * @description Số quan sát hợp lệ của input chính, không phải số hàng hiển thị
             */
            n: number;
            /** Caveats */
            caveats?: string[];
            filters: components["schemas"]["ScaleYearFilters"];
        };
        /** OverviewMetrics */
        OverviewMetrics: {
            /** Mean */
            mean: number | null;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Leader */
            leader: string;
            /** Last */
            last: string;
            /** Gap */
            gap: number | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            meta: components["schemas"]["OverviewMeta"];
            data: components["schemas"]["OverviewData"];
        };
        /** OverviewStoryCards */
        OverviewStoryCards: {
            trend: components["schemas"]["TotalSeriesArtifact"];
            regions: components["schemas"]["RegionMeanArtifact"];
            strongestPair: components["schemas"]["PairArtifact"];
            changeHighlights: components["schemas"]["ChangesArtifact"];
            annualChanges: components["schemas"]["AnnualChangeArtifact"];
            quadrants: components["schemas"]["QuadrantSummaryArtifact"];
            changeDistribution: components["schemas"]["ChangeDistributionArtifact"];
        };
        /** PairArtifact */
        PairArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** X */
            x: string;
            /** Y */
            y: string;
            /** Xmean */
            xMean: number | null;
            /** Ymean */
            yMean: number | null;
            /** Pearsonr */
            pearsonR: number | null;
            /** Rows */
            rows: components["schemas"]["PairRow"][];
        };
        /** PairRow */
        PairRow: {
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
            /**
             * Quadrant
             * @enum {string}
             */
            quadrant: "Cao–cao" | "Thấp–thấp" | "Cao–thấp" | "Thấp–cao";
        };
        /** ProfileArtifact */
        ProfileArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["ProfileRow"][];
        };
        /** ProfileRow */
        ProfileRow: {
            /** Code */
            code: string;
            /** Provincescore */
            provinceScore: number | null;
            /** Regionmean */
            regionMean: number | null;
            /** Nationalmean */
            nationalMean: number | null;
            /** Regionn */
            regionN: number;
            /** Nationaln */
            nationalN: number;
        };
        /** Province */
        Province: {
            /** Provinceid */
            provinceId: number;
            /** Provincevi */
            provinceVi: string;
            /** Provinceen */
            provinceEn: string;
            /** Region */
            region: string;
            /** Regionid */
            regionId: number;
        };
        /** ProvinceAvailability */
        ProvinceAvailability: {
            /** Regions */
            regions: string[];
            /** Provinces */
            provinces: string[];
        };
        /** ProvinceFilters */
        ProvinceFilters: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "six" | "eight";
            /** Year */
            year: number;
            /** Region */
            region: string;
            /** Province */
            province: string;
        };
        /** ProvinceInsights */
        ProvinceInsights: {
            /** Distribution */
            distribution: string;
            /** Ranking */
            ranking: string;
            /** Benchmark */
            benchmark: string;
            /** Profile */
            profile: string;
        };
        /** ProvincesData */
        ProvincesData: {
            measure: components["schemas"]["Measure"];
            distribution: components["schemas"]["DistributionArtifact"];
            regionMeans: components["schemas"]["RegionMeanArtifact"];
            ranking: components["schemas"]["RankingRowsArtifact"];
            benchmark: components["schemas"]["Benchmark"];
            profile: components["schemas"]["ProfileArtifact"];
            availability: components["schemas"]["ProvinceAvailability"];
            insights: components["schemas"]["ProvinceInsights"];
        };
        /** ProvincesMeta */
        ProvincesMeta: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "v1";
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /**
             * N
             * @description Số quan sát hợp lệ của input chính, không phải số hàng hiển thị
             */
            n: number;
            /** Caveats */
            caveats?: string[];
            filters: components["schemas"]["ProvinceFilters"];
        };
        /** ProvincesResponse */
        ProvincesResponse: {
            meta: components["schemas"]["ProvincesMeta"];
            data: components["schemas"]["ProvincesData"];
        };
        /** QuadrantSummaryArtifact */
        QuadrantSummaryArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** X */
            x: string;
            /** Y */
            y: string;
            /** Pearsonr */
            pearsonR: number | null;
            /** Rows */
            rows: components["schemas"]["QuadrantSummaryRow"][];
        };
        /** QuadrantSummaryRow */
        QuadrantSummaryRow: {
            /** Label */
            label: string;
            /** N */
            n: number;
            /** Percentage */
            percentage: number;
            /** Provinces */
            provinces: string[];
        };
        /** RankingArtifact */
        RankingArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["RankingRow"][];
            /** Top10 */
            top10: components["schemas"]["RankingRow"][];
            /** Bottom10 */
            bottom10: components["schemas"]["RankingRow"][];
        };
        /** RankingRow */
        RankingRow: {
            /** Provinceid */
            provinceId: number;
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Rank */
            rank: number;
        };
        /** RankingRowsArtifact */
        RankingRowsArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["RegionalRankingRow"][];
        };
        /** RegionMeanArtifact */
        RegionMeanArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["RegionMeanRow"][];
        };
        /** RegionMeanRow */
        RegionMeanRow: {
            /** Region */
            region: string;
            /** Meanscore */
            meanScore: number | null;
            /** Medianscore */
            medianScore: number | null;
            /** Q1 */
            q1: number | null;
            /** Q3 */
            q3: number | null;
            /** Iqr */
            iqr: number | null;
            /** Minscore */
            minScore: number | null;
            /** Maxscore */
            maxScore: number | null;
            /** N */
            n: number;
            /** Spread */
            spread: number | null;
        };
        /** RegionalPoint */
        RegionalPoint: {
            /** Year */
            year: number;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Contributorn */
            contributorN: number;
        };
        /** RegionalRankArtifact */
        RegionalRankArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["RegionalRankPoint"][];
        };
        /** RegionalRankPoint */
        RegionalRankPoint: {
            /** Year */
            year: number;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Contributorn */
            contributorN: number;
            /** Rank */
            rank: number;
        };
        /** RegionalRankingRow */
        RegionalRankingRow: {
            /** Provinceid */
            provinceId: number;
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Rankregion */
            rankRegion: number;
        };
        /** RegionalSeriesArtifact */
        RegionalSeriesArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["RegionalPoint"][];
        };
        /** RegionalYearOverYearArtifact */
        RegionalYearOverYearArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["RegionalYearOverYearPoint"][];
        };
        /** RegionalYearOverYearPoint */
        RegionalYearOverYearPoint: {
            /** Year */
            year: number;
            /** Region */
            region: string;
            /** Score */
            score: number | null;
            /** Contributorn */
            contributorN: number;
            /** Previousscore */
            previousScore: number | null;
            /** Change */
            change: number | null;
        };
        /** RegressionArtifact */
        RegressionArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** X */
            x: string;
            /** Y */
            y: string;
            /** Slope */
            slope: number | null;
            /** Intercept */
            intercept: number | null;
            /** Rsquared */
            rSquared: number | null;
            /** Strength */
            strength: string;
            /** Largestresidualprovince */
            largestResidualProvince: string;
            /** Rows */
            rows: components["schemas"]["RegressionRow"][];
        };
        /** RegressionRow */
        RegressionRow: {
            /** Provincevi */
            provinceVi: string;
            /** Region */
            region: string;
            /** X */
            x: number | null;
            /** Y */
            y: number | null;
            /** Predicted */
            predicted: number | null;
            /** Residual */
            residual: number | null;
        };
        /** ScaleAvailability */
        ScaleAvailability: {
            /**
             * Id
             * @enum {string}
             */
            id: "six" | "eight";
            /** Label */
            label: string;
            /** Years */
            years: number[];
            /** Dimensions */
            dimensions: string[];
            /** Totalcolumn */
            totalColumn: string;
        };
        /** ScaleYearFilters */
        ScaleYearFilters: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "six" | "eight";
            /** Year */
            year: number;
        };
        /** StableClusterArtifact */
        StableClusterArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** N */
            n: number;
            /** Selectedk */
            selectedK: number;
            /**
             * Selectionmode
             * @enum {string}
             */
            selectionMode: "auto" | "manual";
            /** Silhouette */
            silhouette: number | null;
            /**
             * Randomstate
             * @constant
             */
            randomState: 42;
            /** Candidatescores */
            candidateScores: components["schemas"]["ClusterCandidate"][];
            /** Pcavariance */
            pcaVariance: number[];
            /** Assignments */
            assignments: components["schemas"]["ClusterAssignment"][];
            /** Centroids */
            centroids: components["schemas"]["StableClusterCentroid"][];
            /** Transitions */
            transitions: components["schemas"]["ClusterTransition"][];
        };
        /** StableClusterCentroid */
        StableClusterCentroid: {
            /** Cluster */
            cluster: string;
            /** Nstart */
            nStart: number;
            /** Nend */
            nEnd: number;
            /** Descriptor */
            descriptor: string;
            /** Values */
            values: components["schemas"]["ClusterCentroidValue"][];
        };
        /** StdArtifact */
        StdArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["StdRow"][];
        };
        /** StdRow */
        StdRow: {
            /** Code */
            code: string;
            /** Meanscore */
            meanScore: number | null;
            /** Stdscore */
            stdScore: number | null;
            /** Minscore */
            minScore: number | null;
            /** Maxscore */
            maxScore: number | null;
            /** N */
            n: number;
        };
        /** TotalPoint */
        TotalPoint: {
            /** Year */
            year: number;
            /** Score */
            score: number | null;
            /** Contributorn */
            contributorN: number;
        };
        /** TotalSeriesArtifact */
        TotalSeriesArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["TotalPoint"][];
        };
        /** TotalSummary */
        TotalSummary: {
            /** First */
            first: number | null;
            /** Latest */
            latest: number | null;
            /** Vfirst */
            vFirst: number | null;
            /** Vlatest */
            vLatest: number | null;
            /** Net */
            net: number | null;
            /** Peakyear */
            peakYear: number | null;
            /** Peakvalue */
            peakValue: number | null;
            /** Dipvalue */
            dipValue: number | null;
        };
        /** TrendFilters */
        TrendFilters: {
            /**
             * Scale
             * @enum {string}
             */
            scale: "six" | "eight";
            /** From */
            from: number;
            /** To */
            to: number;
            /** Region */
            region?: string | null;
            /** Province */
            province?: string | null;
        };
        /** TrendInsights */
        TrendInsights: {
            /** Total */
            total: string;
            /** Regionalyearoveryear */
            regionalYearOverYear: string;
            /** Regionalrank */
            regionalRank: string;
            /** Dimensions */
            dimensions: string;
        };
        /** TrendsData */
        TrendsData: {
            measure: components["schemas"]["Measure"];
            summary: components["schemas"]["TotalSummary"];
            totalSeries: components["schemas"]["TotalSeriesArtifact"];
            dimensionSeries: components["schemas"]["DimensionSeriesArtifact"];
            dimensionDeltas: components["schemas"]["DeltaArtifact"];
            covid: components["schemas"]["CovidArtifact"];
            heatmap: components["schemas"]["DimensionSeriesArtifact"];
            regionalSeries: components["schemas"]["RegionalSeriesArtifact"];
            regionalYearOverYear: components["schemas"]["RegionalYearOverYearArtifact"];
            regionalRanks: components["schemas"]["RegionalRankArtifact"];
            selectedSeries: components["schemas"]["FocusSeriesArtifact"];
            turningPoints: components["schemas"]["TurningPointArtifact"];
            insights: components["schemas"]["TrendInsights"];
        };
        /** TrendsMeta */
        TrendsMeta: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "v1";
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /**
             * N
             * @description Số quan sát hợp lệ của input chính, không phải số hàng hiển thị
             */
            n: number;
            /** Caveats */
            caveats?: string[];
            filters: components["schemas"]["TrendFilters"];
        };
        /** TrendsResponse */
        TrendsResponse: {
            meta: components["schemas"]["TrendsMeta"];
            data: components["schemas"]["TrendsData"];
        };
        /** TurningPoint */
        TurningPoint: {
            /** Year */
            year: number;
            /** Fromyear */
            fromYear: number;
            /** Score */
            score: number | null;
            /** Previousscore */
            previousScore: number | null;
            /** Change */
            change: number | null;
        };
        /** TurningPointArtifact */
        TurningPointArtifact: {
            /** Rowcount */
            rowCount: number;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Caveats */
            caveats?: string[];
            /** Rows */
            rows: components["schemas"]["TurningPoint"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_metadata_api_v1_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_geojson_api_v1_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeojsonResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_overview_api_v1_overview_get: {
        parameters: {
            query?: {
                scale?: "six" | "eight";
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trends_api_v1_trends_get: {
        parameters: {
            query?: {
                scale?: "six" | "eight";
                from?: number | null;
                to?: number | null;
                region?: string | null;
                province?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_provinces_api_v1_provinces_get: {
        parameters: {
            query?: {
                scale?: "six" | "eight";
                year?: number | null;
                region?: string | null;
                province?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvincesResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dimensions_api_v1_dimensions_get: {
        parameters: {
            query?: {
                scale?: "six" | "eight";
                year?: number | null;
                x?: string | null;
                y?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DimensionsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dynamics_api_v1_dynamics_get: {
        parameters: {
            query?: {
                scale?: "six" | "eight";
                from?: number | null;
                to?: number | null;
                k?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DynamicsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
