import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import type { ReactNode } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom'
import { beforeEach, expect, it, vi } from 'vitest'
import { Dimension } from './Dimension'
import { Dynamics } from './Dynamics'
import { api, type DimensionsResponse, type DynamicsResponse, type MetadataResponse } from '../api/client'

vi.mock('../components/CartesianChart', () => ({ CartesianChart: ({ title, onClick, children }: { title: string; onClick?: (event: { points: Array<{ pointNumber: number[]; pointIndex: number[] }> }) => void; children?: ReactNode }) => <section aria-label={title}><button onClick={() => onClick?.({ points: [{ pointNumber: [0, 1], pointIndex: [1, 0] }] })}>Chọn điểm {title}</button>{children}</section> }))
vi.mock('../api/client', async (importOriginal) => { const actual = await importOriginal<typeof import('../api/client')>(); return { ...actual, api: { metadata: vi.fn(), dimensions: vi.fn(), dynamics: vi.fn() } } })

const metadata = { meta: { source: 'PAPI', unit: 'điểm', n: 2, caveats: [], filters: {}, schemaVersion: 'v1' }, data: { scales: [{ id: 'six', label: '6', years: [2011, 2024], dimensions: ['D1', 'D2'], totalColumn: 'total' }, { id: 'eight', label: '8', years: [2018, 2024], dimensions: ['D1', 'D2'], totalColumn: 'total8' }], dimensions: [{ code: 'D1', nameVi: 'Tham gia', nameEn: 'Participation', short: 'Tham gia', color: '#000', sort: 1, fromYear: 2011 }, { code: 'D2', nameVi: 'Minh bạch', nameEn: 'Transparency', short: 'Minh bạch', color: '#111', sort: 2, fromYear: 2011 }], regions: [], provinces: [] } } as MetadataResponse
const dimensions = { meta: { source: 'PAPI', unit: 'điểm lĩnh vực PAPI', n: 2, caveats: ['Không nhân quả'], schemaVersion: 'v1', filters: { scale: 'six', year: 2024, x: 'D2', y: 'D1' } }, data: { availability: { dimensions: ['D1', 'D2'] }, correlation: { rowCount: 2, unit: 'không đơn vị', source: 'PAPI', caveats: [], n: 2, codes: ['D1', 'D2'], matrix: [[1, .5], [.5, 1]] }, pair: { rowCount: 2, unit: 'điểm lĩnh vực PAPI', source: 'PAPI', caveats: [], n: 2, x: 'D2', y: 'D1', xMean: 2, yMean: 2, pearsonR: .5, rows: [{ provinceVi: 'An Giang', region: 'Nam', x: 1, y: 2, quadrant: 'Thấp–cao' }, { provinceVi: 'Bắc Giang', region: 'Bắc', x: 3, y: 2, quadrant: 'Cao–cao' }] }, standardDeviation: { rowCount: 2, unit: 'điểm lĩnh vực PAPI', source: 'PAPI', caveats: [], rows: [{ code: 'D1', meanScore: 2, stdScore: .3, n: 2 }, { code: 'D2', meanScore: 2, stdScore: .4, n: 2 }] }, regression: { rowCount: 2, unit: 'điểm lĩnh vực PAPI', source: 'PAPI', n: 2, x: 'D2', y: 'D1', slope: .5, intercept: 1, rSquared: .25, strength: 'khá mạnh', largestResidualProvince: 'An Giang', rows: [{ provinceVi: 'An Giang', region: 'Nam', x: 1, y: 2, predicted: 1.5, residual: .5 }, { provinceVi: 'Bắc Giang', region: 'Bắc', x: 3, y: 2, predicted: 2.5, residual: -.5 }] }, labels: metadata.data.dimensions } } satisfies DimensionsResponse
const dynamics = { meta: { source: 'PAPI', unit: 'điểm tổng', n: 2, caveats: ['Không xếp hạng'], schemaVersion: 'v1', filters: { scale: 'six', from: 2011, to: 2024, k: 'auto' } }, data: { measure: { id: 'total', label: 'Tổng', unit: 'điểm tổng' }, changes: { rowCount: 2, unit: 'chênh lệch điểm PAPI', source: 'PAPI', caveats: [], n: 2, median: 0, rows: [{ provinceVi: 'An Giang', region: 'Nam', fromScore: 2, toScore: 3, change: 1 }, { provinceVi: 'Bắc Giang', region: 'Bắc', fromScore: 3, toScore: 2, change: -1 }], top8: [{ provinceVi: 'An Giang', region: 'Nam', fromScore: 2, toScore: 3, change: 1 }], bottom8: [{ provinceVi: 'Bắc Giang', region: 'Bắc', fromScore: 3, toScore: 2, change: -1 }] }, clusters: { rowCount: 2, unit: 'điểm lĩnh vực PAPI', source: 'PAPI', caveats: ['KMeans'], n: 2, count: 2, randomState: 42, rows: [], centroids: [{ cluster: '0', n: 1, D1: 1, D2: 3 }, { cluster: '1', n: 1, D1: 3, D2: 1 }], profiles: [{ cluster: '0', n: 1, provinces: [{ provinceVi: 'An Giang', region: 'Nam' }] }, { cluster: '1', n: 1, provinces: [{ provinceVi: 'Bắc Giang', region: 'Bắc' }] }] }, clusterModel: { rowCount: 2, unit: 'profile chuẩn hóa', source: 'PAPI', n: 2, selectedK: 2, selectionMode: 'auto', silhouette: .5, randomState: 42, candidateScores: [{ k: 2, silhouette: .5 }], pcaVariance: [.7, .3], assignments: [{ provinceVi: 'An Giang', region: 'Nam', startCluster: 'A', endCluster: 'B', changed: true, startPc1: -1, startPc2: 0, endPc1: 1, endPc2: 0 }, { provinceVi: 'Bắc Giang', region: 'Bắc', startCluster: 'B', endCluster: 'A', changed: true, startPc1: 1, startPc2: 0, endPc1: -1, endPc2: 0 }], centroids: [{ cluster: 'A', nStart: 1, nEnd: 1, descriptor: 'Mạnh D1', values: [{ code: 'D1', zScore: 1, rawScore: 3 }] }, { cluster: 'B', nStart: 1, nEnd: 1, descriptor: 'Mạnh D2', values: [{ code: 'D2', zScore: 1, rawScore: 3 }] }], transitions: [{ fromCluster: 'A', toCluster: 'B', n: 1, provinces: ['An Giang'] }, { fromCluster: 'B', toCluster: 'A', n: 1, provinces: ['Bắc Giang'] }] } } } satisfies DynamicsResponse
function Here() { return <output data-testid="url">{useLocation().search}</output> }
function page(path: string, element: ReactNode) { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="*" element={<>{element}<Here /></>} /></Routes></MemoryRouter></QueryClientProvider>) }
beforeEach(() => { vi.resetAllMocks(); vi.mocked(api.metadata).mockResolvedValue(metadata); vi.mocked(api.dimensions).mockImplementation((scale, year, x, y) => Promise.resolve({ ...dimensions, meta: { ...dimensions.meta, filters: { scale, year, x, y } } })); vi.mocked(api.dynamics).mockImplementation((scale, from, to, k) => Promise.resolve({ ...dynamics, meta: { ...dynamics.meta, filters: { scale, from, to, k: k ?? 'auto' } } })) })

it('H3 chuẩn hóa URL, giữ tỉnh, render bốn chart và xử lý click heatmap đổi X/Y', async () => { const user = userEvent.setup(); page('/dimension?scale=six&year=2024&x=sai&y=sai&province=An%20Giang', <Dimension />); await screen.findByRole('heading', { name: /Cùng biến thiên/ }); await waitFor(() => expect(screen.getByTestId('url')).toHaveTextContent('x=D2&y=D1&province=An+Giang')); await user.click(screen.getByRole('button', { name: /Chọn điểm Ma trận/ })); await waitFor(() => expect(api.dimensions).toHaveBeenCalledWith('six', 2024, 'D1', 'D2')); expect(screen.getByLabelText('Phân tán theo hai lĩnh vực')).toBeInTheDocument(); expect(screen.getByLabelText('Độ phân tán theo lĩnh vực')).toBeInTheDocument(); expect(screen.getByLabelText('Sai lệch so với đường hồi quy')).toBeInTheDocument() })
it('H3 hiển thị lỗi FastAPI có thể phục hồi', async () => { vi.mocked(api.dimensions).mockRejectedValueOnce(new Error('FastAPI dừng')); page('/dimension?scale=six&year=2024&x=D1&y=D2', <Dimension />); expect(await screen.findByRole('alert')).toHaveTextContent('FastAPI dừng') })
it('H3 có trạng thái tải công bố được', async () => { vi.mocked(api.metadata).mockImplementationOnce(() => new Promise(() => undefined)); page('/dimension?scale=six', <Dimension />); expect(await screen.findByRole('status', { name: 'Đang tải mối quan hệ lĩnh vực' })).toBeInTheDocument() })
it('H3 retry thành công', async () => { const user = userEvent.setup(); vi.mocked(api.dimensions).mockRejectedValueOnce(new Error('Lỗi tạm thời')); page('/dimension?scale=six&year=2024&x=D1&y=D2', <Dimension />); await user.click(await screen.findByRole('button', { name: 'Thử lại' })); expect(await screen.findByRole('heading', { name: /Cùng biến thiên/ })).toBeInTheDocument() })
it('H4 chuẩn hóa range, mở bảng tìm kiếm và chọn hồ sơ bằng heatmap', async () => { const user = userEvent.setup(); page('/dynamics?scale=eight&from=2011&to=2011&province=An%20Giang', <Dynamics />); await screen.findByRole('heading', { name: /Điểm thay đổi/ }); await waitFor(() => expect(screen.getByTestId('url')).toHaveTextContent('scale=eight&from=2018&to=2024&province=An+Giang')); await user.click(screen.getByText('Xem tất cả tỉnh')); await user.type(screen.getByRole('textbox', { name: 'Tìm tỉnh' }), 'Bắc'); expect(screen.getAllByText('Bắc Giang').length).toBeGreaterThan(1); expect(screen.getByText(/Điểm cao nhất ở Minh bạch/)).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: /Chọn điểm Bản đồ nhiệt/ })); expect(await screen.findByText(/Hồ sơ B: 1 tỉnh/)).toBeInTheDocument() })
it('H4 chọn Hồ sơ B bằng bàn phím và cập nhật danh sách', async () => { const user = userEvent.setup(); page('/dynamics?scale=six&from=2011&to=2024', <Dynamics />); const profileB = await screen.findByRole('button', { name: 'Hồ sơ B' }); profileB.focus(); await user.keyboard('{Enter}'); expect(profileB).toHaveAttribute('aria-pressed', 'true'); expect(await screen.findByText(/Hồ sơ B: 1 tỉnh/)).toBeInTheDocument() })
it('H3 năm đầu tạo CTA H4 với hai mốc hợp lệ', async () => { page('/dimension?scale=eight&year=2018&x=D1&y=D2&province=An%20Giang', <Dimension />); const link = await screen.findByRole('link', { name: /Mở Thay đổi/ }); expect(link).toHaveAttribute('href', '/dynamics?scale=eight&from=2018&to=2024&province=An%20Giang') })
it('H4 hiển thị lỗi FastAPI có thể phục hồi', async () => { vi.mocked(api.dynamics).mockRejectedValueOnce(new Error('FastAPI dừng')); page('/dynamics?scale=six&from=2011&to=2024', <Dynamics />); expect(await screen.findByRole('alert')).toHaveTextContent('FastAPI dừng') })
it('H4 có trạng thái tải và rỗng', async () => { vi.mocked(api.metadata).mockImplementationOnce(() => new Promise(() => undefined)); const loading = page('/dynamics?scale=six', <Dynamics />); expect(await screen.findByRole('status', { name: 'Đang tải thay đổi và phân nhóm' })).toBeInTheDocument(); await waitFor(() => expect(api.metadata).toHaveBeenCalledTimes(1)); loading.unmount(); vi.mocked(api.dynamics).mockImplementation(() => Promise.resolve({ ...dynamics, data: { ...dynamics.data, changes: { ...dynamics.data.changes, rows: [] } } })); page('/dynamics?scale=six&from=2011&to=2024', <Dynamics />); expect(await screen.findByRole('heading', { name: /Chưa có dữ liệu thay đổi/ })).toBeInTheDocument() })
it('H4 retry thành công', async () => { const user = userEvent.setup(); vi.mocked(api.dynamics).mockRejectedValueOnce(new Error('Lỗi tạm thời')); page('/dynamics?scale=six&from=2011&to=2024', <Dynamics />); await user.click(await screen.findByRole('button', { name: 'Thử lại' })); expect(await screen.findByRole('heading', { name: /Điểm thay đổi/ })).toBeInTheDocument() })
