import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import type { ReactNode } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom'
import { vi } from 'vitest'
import { TimeTrend } from './TimeTrend'
import { Provincial } from './Provincial'
import { api, type GeojsonResponse, type MetadataResponse, type ProvincesResponse, type TrendsResponse } from '../api/client'

vi.mock('react-plotly.js/factory', () => ({ default: () => () => <div data-testid="plot" /> }))
vi.mock('plotly.js-geo-dist-min', () => ({ default: {} }))
vi.mock('../api/client', async (importOriginal) => {
  const actual = await importOriginal<typeof import('../api/client')>()
  return { ...actual, api: { metadata: vi.fn(), geojson: vi.fn(), trends: vi.fn(), provinces: vi.fn() } }
})

const meta = { source: 'PAPI', unit: 'điểm', n: 2, caveats: [] as string[], filters: {}, schemaVersion: 'v1' as const }
const metadata = { meta, data: { scales: [{ id: 'six', label: '6', years: [2011, 2024], dimensions: ['d1'], totalColumn: 'total' }, { id: 'eight', label: '8', years: [2018, 2024], dimensions: ['d1'], totalColumn: 'total8' }], dimensions: [{ code: 'd1', nameVi: 'Tham gia', nameEn: 'Participation', short: 'D1', color: '#000', sort: 1, fromYear: 2011 }], regions: ['Bắc', 'Nam'], provinces: [{ provinceId: 1, provinceVi: 'An Giang', provinceEn: 'An Giang', region: 'Nam', regionId: 1 }, { provinceId: 2, provinceVi: 'Bắc Giang', provinceEn: 'Bac Giang', region: 'Bắc', regionId: 2 }] } } satisfies MetadataResponse
const geojson = { meta: { ...meta, unit: 'địa giới' }, data: { geojson: { type: 'FeatureCollection', features: [] } } } satisfies GeojsonResponse
const trends = { meta: { ...meta, filters: { scale: 'six', from: 2011, to: 2024, region: null, province: null } }, data: { measure: { id: 'total', label: 'Tổng', unit: 'điểm' }, summary: { first: 1, latest: 2, vFirst: 1, vLatest: 2, net: 1, peakYear: 2024, peakValue: 2, dipValue: 1 }, totalSeries: { rowCount: 2, unit: 'điểm', source: 'PAPI', rows: [{ year: 2011, score: 1, contributorN: 2 }, { year: 2024, score: 2, contributorN: 2 }] }, dimensionSeries: { rowCount: 2, unit: 'điểm', source: 'PAPI', rows: [{ year: 2011, code: 'd1', label: 'Tham gia', score: 1, contributorN: 2 }, { year: 2024, code: 'd1', label: 'Tham gia', score: 2, contributorN: 2 }] }, dimensionDeltas: { rowCount: 1, unit: 'điểm', source: 'PAPI', rows: [{ code: 'd1', label: 'Tham gia', delta: 1, fromScore: 1, toScore: 2, contributorNFrom: 2, contributorNTo: 2 }] }, covid: { rowCount: 0, unit: 'điểm', source: 'PAPI', available: false, rows: [] }, heatmap: { rowCount: 2, unit: 'điểm', source: 'PAPI', rows: [{ year: 2011, code: 'd1', label: 'Tham gia', score: 1, contributorN: 2 }, { year: 2024, code: 'd1', label: 'Tham gia', score: 2, contributorN: 2 }] }, regionalSeries: { rowCount: 0, unit: 'điểm', source: 'PAPI', rows: [] }, regionalYearOverYear: { rowCount: 0, unit: 'điểm', source: 'PAPI', rows: [] }, regionalRanks: { rowCount: 0, unit: 'hạng vùng', source: 'PAPI', rows: [] }, selectedSeries: { rowCount: 0, unit: 'điểm', source: 'PAPI', rows: [] }, turningPoints: { rowCount: 0, unit: 'điểm', source: 'PAPI', rows: [] }, insights: { total: 'Điểm tăng 1,00.', regionalYearOverYear: 'Chưa đủ dữ liệu vùng.', regionalRank: 'Thứ tự vùng ổn định.', dimensions: 'Tham gia tăng mạnh nhất.' } } } satisfies TrendsResponse
const provinces = { meta: { ...meta, filters: { scale: 'eight', year: 2024, region: 'Nam', province: 'An Giang' } }, data: { measure: { id: 'total8', label: 'Tổng', unit: 'điểm' }, distribution: { rowCount: 2, unit: 'điểm', source: 'PAPI', rows: [{ provinceId: 1, provinceVi: 'An Giang', region: 'Nam', score: 2, year: 2024, rank: 1 }, { provinceId: 2, provinceVi: 'Bắc Giang', region: 'Bắc', score: 1, year: 2024, rank: 2 }] }, regionMeans: { rowCount: 2, unit: 'điểm', source: 'PAPI', rows: [] }, ranking: { rowCount: 1, unit: 'điểm', source: 'PAPI', rows: [{ provinceId: 1, provinceVi: 'An Giang', region: 'Nam', score: 2, rankRegion: 1 }] }, benchmark: { unit: 'điểm', source: 'PAPI', provinceScore: 2, regionMean: 2, nationalMean: 1.5, nationalMin: 1, nationalMax: 2, nationalQ1: 1.25, nationalQ3: 1.75, vsRegion: 0, vsNational: .5, regionN: 1, nationalN: 2, rankRegion: 1, regionTotal: 1 }, profile: { rowCount: 1, unit: 'điểm', source: 'PAPI', rows: [{ code: 'd1', provinceScore: 2, regionMean: 2, nationalMean: 1.5, regionN: 1, nationalN: 2 }] }, availability: { regions: ['Bắc', 'Nam'], provinces: ['An Giang'] }, insights: { distribution: 'Nam có trung vị cao nhất.', ranking: 'An Giang dẫn đầu vùng.', benchmark: 'An Giang cao hơn toàn bộ mẫu.', profile: 'Tham gia bằng trung bình vùng.' } } } satisfies ProvincesResponse

function Here() { return <output data-testid="url">{useLocation().search}</output> }
function page(path: string, element: ReactNode) { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><MemoryRouter initialEntries={[path]} future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><Routes><Route path="*" element={<>{element}<Here /></>} /></Routes></MemoryRouter></QueryClientProvider>) }
beforeEach(() => { vi.clearAllMocks(); vi.mocked(api.metadata).mockResolvedValue(metadata); vi.mocked(api.geojson).mockResolvedValue(geojson); vi.mocked(api.trends).mockResolvedValue(trends); vi.mocked(api.provinces).mockImplementation((scale, year, region) => Promise.resolve({ ...provinces, meta: { ...provinces.meta, filters: { scale, year, region: region ?? 'Nam', province: 'An Giang' } } })) })

it('H1 chuẩn hóa khoảng năm và truyền context tỉnh/vùng vào API overlay', async () => { page('/time-trend?scale=eight&from=2011&to=2011&province=An%20Giang', <TimeTrend />); await screen.findByRole('heading', { name: /Điểm quản trị thay đổi khi nào/ }); await waitFor(() => expect(screen.getByTestId('url')).toHaveTextContent('scale=eight&from=2018&to=2024&province=An+Giang')); expect(api.trends).toHaveBeenCalledWith('eight', 2018, 2024, 'Nam', 'An Giang') })
it('H1 nhận alias year từ Tổng quan và dùng đầu chuỗi làm mốc đầu', async () => { page('/time-trend?scale=six&year=2024', <TimeTrend />); await screen.findByRole('heading', { name: /Điểm quản trị thay đổi khi nào/ }); await waitFor(() => expect(screen.getByTestId('url')).toHaveTextContent('scale=six&from=2011&to=2024')); expect(api.trends).toHaveBeenCalledWith('six', 2011, 2024, undefined, undefined) })
it('H1 mặc định render đúng bốn câu hỏi và bốn insight', async () => { page('/time-trend', <TimeTrend />); await screen.findByRole('heading', { name: /Điểm quản trị thay đổi khi nào/ }); expect(api.trends).toHaveBeenCalledWith('six', 2011, 2024, undefined, undefined); expect(screen.getByRole('heading', { name: 'Điểm trung bình các tỉnh tăng, giảm hay ổn định?' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Năm nào nhiều vùng cùng tăng hoặc cùng giảm?' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Thứ tự sáu vùng thay đổi ra sao?' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Lĩnh vực nào cải thiện hoặc suy giảm mạnh nhất?' })).toBeInTheDocument(); expect(screen.getAllByLabelText('Insight biểu đồ')).toHaveLength(4) })
it('H2 chuẩn hóa region/province và đổi scale thì dùng năm hợp lệ, đồng thời giữ selection hợp lệ', async () => { const user = userEvent.setup(); page('/provincial?scale=eight&year=2011&region=Sai&province=Sai', <Provincial />); await screen.findByRole('heading', { name: /Khác biệt giữa vùng/ }); await waitFor(() => expect(screen.getByTestId('url')).toHaveTextContent('scale=eight&year=2024&region=Nam&province=An+Giang')); expect(api.provinces).toHaveBeenCalledWith('eight', 2024, undefined); await user.selectOptions(await screen.findByRole('combobox', { name: 'Phạm vi so sánh' }), 'six'); await waitFor(() => expect(screen.getByTestId('url')).toHaveTextContent('scale=six&year=2024&region=Nam&province=An+Giang')); expect(api.provinces).toHaveBeenLastCalledWith('six', 2024, 'Nam', 'An Giang') })
it('H2 render đúng bốn câu hỏi, bốn insight và bốn nút phóng to', async () => { page('/provincial?scale=eight&year=2024', <Provincial />); await waitFor(() => expect(api.provinces).toHaveBeenCalledWith('eight', 2024, 'Nam', 'An Giang')); await screen.findByRole('heading', { name: /An Giang đứng ở đâu trong Nam/ }); expect(screen.getByRole('heading', { name: 'Vùng nào có mặt bằng cao và phân hóa rộng nhất?' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Điểm tỉnh cách vùng và toàn bộ mẫu bao xa?' })).toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Tỉnh mạnh hoặc yếu ở lĩnh vực nào so với vùng?' })).toBeInTheDocument(); expect(screen.getAllByLabelText('Insight biểu đồ')).toHaveLength(4); expect(screen.getAllByRole('button', { name: /Phóng to biểu đồ/ })).toHaveLength(4) })
it('H1 hiển thị lỗi và thử lại được', async () => { const user = userEvent.setup(); vi.mocked(api.trends).mockRejectedValueOnce(new Error('FastAPI dừng')); page('/time-trend?scale=six&from=2011&to=2024', <TimeTrend />); expect(await screen.findByRole('alert')).toHaveTextContent('FastAPI dừng'); await user.click(screen.getByRole('button', { name: 'Thử lại' })); expect(await screen.findByRole('heading', { name: /Điểm quản trị thay đổi khi nào/ })).toBeInTheDocument() })
it('H2 hiển thị lỗi và thử lại được', async () => { const user = userEvent.setup(); vi.mocked(api.provinces).mockRejectedValueOnce(new Error('FastAPI dừng')); page('/provincial?scale=eight&year=2024', <Provincial />); expect(await screen.findByRole('alert')).toHaveTextContent('FastAPI dừng'); await user.click(screen.getByRole('button', { name: 'Thử lại' })); expect(await screen.findByRole('heading', { name: /Khác biệt giữa vùng/ })).toBeInTheDocument() })
it('H1 và H2 có trạng thái tải công bố được', () => { vi.mocked(api.metadata).mockImplementation(() => new Promise(() => undefined)); const one = page('/time-trend?scale=six&from=2011&to=2024', <TimeTrend />); expect(screen.getByRole('status', { name: 'Đang tải diễn biến' })).toBeInTheDocument(); one.unmount(); const two = page('/provincial?scale=six&year=2024', <Provincial />); expect(screen.getByRole('status', { name: 'Đang tải vùng và tỉnh' })).toBeInTheDocument(); two.unmount() })
it('H1 có trạng thái rỗng không render biểu đồ', async () => { vi.mocked(api.trends).mockResolvedValue({ ...trends, data: { ...trends.data, totalSeries: { ...trends.data.totalSeries, rows: [] } } }); page('/time-trend?scale=six&from=2011&to=2024', <TimeTrend />); expect(await screen.findByRole('heading', { name: /Chưa có diễn biến/ })).toBeInTheDocument() })
